### ISSUE TITLE
rtnetlink: release v1.0.0

### ISSUE THREAD

**Issue by jsimonetti** [jsimonetti/rtnetlink#23]
Following netlinks v1.0.0 release I think it is only proper to release v1.0.0 of this library aswel.

Watch https://github.com/mdlayher/netlink/issues/123

**Comment by mdlayher** [comment]
For what it's worth, I wouldn't rush to get to 1.0.0 until this package has had more time to bake in projects like dhcp/u-root/etc. It'd be nice, but you never know what sort of API will be most useful and least awkward until some time has been spent using it in a production environment.

I'm only considering doing it with netlink (and maybe genetlink) because they're effectively complete and I don't foresee any more major changes.

**Comment by jsimonetti** [comment]
Good point. I'll wait a bit before calling the API stable and then release v1
