### ISSUE TITLE
rfc: remove constants in favor of "golang.org/x/sys/unix"

### ISSUE THREAD

**Issue by jsimonetti** [jsimonetti/rtnetlink#25]
It looks like all needed rtnetlink constant are available in `golang.org/x/sys/unix`.
I am pondering to remove all the duplicate constants in favor of the ones available there.
This would be a pretty big breaking change so if I decide to do this it should be done before #23.

Any feedback would be welcome.

Tagging some known users and contributors of this lib:
/cc @insomniacslk @terinjokes @mdlayher @rwhelan @yupi

**Comment by jsimonetti** [comment]
It appears 1 constant (`IFA_FLAGS = 0x08`) and 1 set of constants (`OperStateXXX OperationalState`) are missing.

**Comment by mdlayher** [comment]
For netlink, I copied in some of the most commonly used ones like https://godoc.org/github.com/mdlayher/netlink#HeaderFlags and https://godoc.org/github.com/mdlayher/netlink#HeaderType, but in general, I think it's fine for your users to lean on x/sys/unix for most of the constants; especially because rtnetlink is a big API.

For OperState, I was wondering if you could use https://golang.org/pkg/net/#Flags, but it looks like it's a bit more limited.

It's easy enough to add the missing constants to x/sys/unix too, as long as we can find a kernel header.
