### ISSUE TITLE
LinkAttribute's Address and Broadcast types too restrictive

### ISSUE THREAD

**Issue by terinjokes** [jsimonetti/rtnetlink#7]
Currently LinkAttribute's Address and Broadcast members are typed to `net.HardwareAddr`. This aligns with [rtnetlink(7)](https://jlk.fjfi.cvut.cz/arch/manpages/man/core/man-pages/rtnetlink.7.en)'s description of the fields.

However links of type IPIP, IP6IP6, 6to4, GRE over IP, and GRE over IPv6 [contain IP (or IPv6) addresses](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/lib/ll_addr.c#n30) for these fields.

The current implementation checks for the length of a MAC address, making it unable to parse links of any of the above type.

**Comment by jsimonetti** [comment]
I can see when that would be a problem :)

I'm a bit in dubio with how to fix this. We can easily change the length check to include 4, 12 and 16 byte values.

But I wonder if it makes sence to change the field type since it will a BC break.
a `net.HardwareAddr` is just a type around `[]byte` so this would still fit.

What do you think? Should we change the type to `[]byte` and BC break or keep the `net.HardwareAddr` and assume people will know what to do (or read the DOCS) when the link types are of the above mentioned types?

**Comment by jsimonetti** [comment]
I just noticed the length check should be loser anyway as there are a multitude of lengths available for a l link address (f.e. also IP over infiniband which is 20 bytes). I think the best cause of action is to remove the length check altogether (or perhaps check for sane lengths `4 <= len <= 32`) and keep the `net.HardwareAddr` type.

Would you be able to create a PR for this?

**Comment by terinjokes** [comment]
Sure. I'll send a PR today.
